include theme.conf
include mappings.conf

font_size 13
adjust_line_height 175%
tab_bar_edge top

cursor_blink_interval 0
window_padding_width 10
remember_window_size no
initial_window_width 1000
initial_window_height 650
enable_auto_bell no

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url
